name: 'Docker action'
description: 'Docker action'
inputs:
  ebuild:
    required: true
  action:
    required: true
  use:
    required: true
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ebuild }} ${{ inputs.action }} ${{ inputs.use }}
