name: 'Docker action'
description: 'Docker action'
inputs:
  added:
    required: true
  modified:
    required: true
  tool:
    required: true
  action:
    required: false
  params:
    required: false
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.added }}
    - ${{ inputs.modified }}
    - ${{ inputs.tool }}
    - ${{ inputs.action }}
    - ${{ inputs.params }}
