name: 'Docker action'
description: 'Docker action'
inputs:
  added:
    required: true
  modified:
    required: true
  action:
    required: true
  use:
    required: true
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.added }}
    - ${{ inputs.modified }}
    - ${{ inputs.action }}
    - ${{ inputs.use }}
